[package]
name = "hub"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1.28.2", features = ["rt-multi-thread"] }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen-futures = "0.4.37"

[dependencies]
frb_engine = { path = "../frb_engine" }
tokio = { version = "1.28.2", features = ["sync", "macros"] }
async-std = "1.12.0"
serde = { version = "1.0.164", features = ["derive"] }
rmp-serde = "1.1.1"
lazy_static = "1.4.0"
sample_crate = { path = "../sample_crate" }
