[project]
name = "rinf-documentation"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "mkdocs~=1.6.1",
    "mkdocs-material~=9.5.34",
    "mkdocs-awesome-pages-plugin~=2.9.3",
    "mkdocs-glightbox~=0.4.0",
    "mkdocs-git-revision-date-localized-plugin~=1.2.9",
]
